site_name: Digital Anthropic Labs
repo_url: https://github.com/Digital-Anthropic
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
  - Home: README.md
  - Terraform:
    - Terraform Intro: terraform/theory/README_Terraform_Intro.md
    - Terraform Lab: terraform/theory/README.md
    - Terraform Installation: terraform/theory/README_Instalation.md
    - Terraform Demo: terraform/demos/README.md

plugins:
  - social
  - search