name: Markdown Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y npm
        npm install -g markdownlint-cli

    - name: Lint Markdown files
      run: |
        markdownlint '**/*.md' --config .markdownlint.json || exit 1

    - name: Upload artifact if linting fails
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: lint-failure
        path: .
